name: idpconfgen
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.7,<3.10
    - numpy=1
    - numba>=0.53.0
    - pybind11=2
    - scipy=1
    - matplotlib=3
    - pip
    - tox=3
    - pip:
        - tox-conda
