@startuml

start

:idpconfgen //segsplit//;

partition #LIGHTGREY Examples {
    #WHITE:$ idpconfgen segsplit filtered_pdbs/ -d split_pdbs/ -n;
    #WHITE:$ idpconfgen segsplit filtered_pdbs/ -ss dssp.pickle -d split_pdbs/ -n;
    #WHITE:$ idpconfgen segsplit filtered_pdbs/ -ss dssp.pickle -d split_pdb.tar -so dssp_split.json -n;
    }

if (input data) then (tar file)
    :unpack tar to tmp dir;
    note left
        expects only //.pdb// files
    end note
    :tmp dir is deleted at the end;
else (folder)
    :uses //.pdb// files in that folder;
endif

if (--complete) then (reads previous)
    :reads previous Sec. Str. information file;
else (not given)
    :starts a blank output file;
endif

fork

:subprocess //mkdssp// on each PDB;
:collect
        residue number,
        Sec Str character,
        FASTA character;
end fork

if (save data to disk) then (JSON)
    :saves dictionary to //.json// file;
else (PICKLE)
    :saves dictionary to //pickle// object;
endif

stop

@enduml
